# Generated by Django 3.2.18 on 2023-03-16 17:04

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0002_alter_booking_total_no_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='activity_type',
            field=models.CharField(choices=[('Team Building Workshop', 'Team Building Workshop'), ('Carnival Team Challenge', 'Carnival Team Challenge'), ('Bridge Building Challenge', 'Bridge Building Challenge')], default='BBC', max_length=256, verbose_name='Activity Type'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 3, 18))], verbose_name='Booking date'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='User name')),
            ],
        ),
    ]
