# Generated by Django 3.2.18 on 2023-03-19 14:34

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_alter_booking_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 3, 21))], verbose_name='Booking date'),
        ),
        migrations.AlterField(
            model_name='review',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Creation date'),
        ),
    ]
