# Generated by Django 3.2.18 on 2023-03-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20230319_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='creation_date',
            field=models.DateField(auto_now_add=True, verbose_name='Creation date'),
        ),
    ]
