# Generated by Django 3.2.18 on 2023-03-20 12:14

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_booking_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-creation_date']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_date',
            field=models.DateTimeField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(datetime.date(2023, 3, 22))], verbose_name='Booking date'),
        ),
    ]
