# Generated by Django 3.2.18 on 2023-03-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20230320_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation date'),
        ),
    ]
